name: Beta docker on dev branch

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches-ignore:
      - 'main'
    paths-ignore:
      - 'CODEOWNERS'
      - '**.md'
      - '.**'

jobs:
  release:
    name: Beta docker on dev branch
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        id: checkout
        # from https://github.com/actions/checkout/commits/main
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Log in to the Container registry
        id: docker_login
        # from https://github.com/docker/login-action/commits/master
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push schedule trigger Docker image
        id: docker_build_push_cron
        # from https://github.com/docker/build-push-action/commits/master
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5
        with:
          context: .
          file: Dockerfile-crontrigger
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:beta-${{ github.ref_name }}-cron
          labels: |
            maintainer=https://pagopa.it
            org.opencontainers.image.source=https://github.com/${{ github.repository }}

      - name: Build and push queue trigger Docker image
        id: docker_build_push_queue
        # from https://github.com/docker/build-push-action/commits/master
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5
        with:
          context: .
          file: Dockerfile-queuetrigger
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:beta-${{ github.ref_name }}-queue
          labels: |
            maintainer=https://pagopa.it
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
